#!/usr/bin/perl
# Twitch media tagger.
# Copyright (c) 2023-2026, Rev. Duncan Ross Palmer (2E0EOL)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#     * Neither the name of the the maintainer, nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

package Retag_tagPerProcess_FakeBackend;
use strict;
use warnings;

our @calls;

sub deleteTags {
	my ($self, $file) = @_;
	push(@calls, [ 'deleteTags', $file ]);
	return;
}

sub readTags {
	my ($self, $file) = @_;
	push(@calls, [ 'readTags', $file ]);
	return {
		artist  => 'Old Artist',
		album   => 'Old Album',
		track   => 'Old Track',
		year    => '2000',
		comment => 'Old Comment',
	};
}

sub writeTags {
	my ($self, @args) = @_;
	push(@calls, [ 'writeTags', @args ]);
	return;
}

package Retag_tagPerProcess_Tests; ## no critic (Modules::ProhibitMultiplePackages)
use strict;
use warnings;
use Moose;

use lib 'externals/libtest-module-runnable-perl/lib';

extends 'Test::Module::Runnable';

use Daybo::Twitch::Retag;
use Daybo::Twitch::TagWrap;
use English qw(-no_match_vars);
use File::Temp qw(tempfile);
use Log::Log4perl qw(:levels);
use POSIX qw(EXIT_SUCCESS);
use Test::Deep qw(cmp_deeply);
use Test::More 0.96;

sub setUp {
	my ($self) = @_;

	@Retag_tagPerProcess_FakeBackend::calls = ();
	$self->sut(Daybo::Twitch::Retag->new());
	$self->sut->__originalProgramName($PROGRAM_NAME);
	$self->sut->_stats({ start_time => 0 });

	return EXIT_SUCCESS;
}

sub testChownFailureWarns {
	my ($self) = @_;
	plan tests => 6;

	my ($fh, $file) = tempfile();
	print {$fh} $self->uniqueStr();
	$fh->close()
	    or die("Cannot close '$file': $ERRNO");

	my $backend = bless({}, 'Retag_tagPerProcess_FakeBackend');
	my @chownArgs;
	$self->mock('Daybo::Twitch::TagWrap', 'getBackendForExt', sub { return $backend });
	$self->mock('Daybo::Twitch::Retag', '__chown', sub {
		my (undef, @args) = @_;
		@chownArgs = @args;
		$ERRNO = 1; ## no critic (Variables::RequireLocalizedPunctuationVars)
		return 0;
	});
	$self->mock('Daybo::Twitch::Logger', 'emit');

	my ($modified, $changeCount);
	eval {
		($modified, $changeCount) = $self->sut->__tagPerProcess(
			$file,
			'mp3',
			50,
			'New Artist',
			'New Album',
			'New Track',
			'2026',
		);
	};

	is($EVAL_ERROR, '', 'does not die when GID restore fails');
	is($modified, 1, 'reports file as modified');
	is($changeCount, 5, 'reports changed tag fields');
	cmp_deeply(\@chownArgs, [ -1, (stat($file))[5], $file ], 'tries to restore original GID');
	cmp_deeply(
		\@Retag_tagPerProcess_FakeBackend::calls,
		[
			[ 'readTags', $file ],
			[ 'deleteTags', $file ],
			[ 'writeTags', $file, 'New Artist', 'New Album', 'New Track', '2026', 'Generated by github.com/daybologic/twitch-tag-media' ],
		],
		'reads, deletes, and writes tags',
	);

	my @warnings = grep({ $_->[0] == $WARN && $_->[1] =~ m/Cannot restore GID/ } @{ $self->mockCalls('Daybo::Twitch::Logger', 'emit') });
	is(scalar(@warnings), 1, 'logs GID restore failure as a warning');

	return EXIT_SUCCESS;
}

package main; ## no critic (Modules::ProhibitMultiplePackages)
use strict;
use warnings;
exit(Retag_tagPerProcess_Tests->new->run);
