#!/usr/bin/perl
# Twitch media tagger.
# Copyright (c) 2023-2026, Rev. Duncan Ross Palmer (2E0EOL)
# All rights reserved.

package Retag_tagPerProcess_Tests;
use strict;
use warnings;
use Moose;

use lib 'externals/libtest-module-runnable-perl/lib';

extends 'Test::Module::Runnable';

use Daybo::Twitch::Retag;
use Daybo::Twitch::TagWrap::Backend::MP3;
use English qw(-no_match_vars);
use File::Temp qw(tempfile);
use POSIX qw(EXIT_SUCCESS);
use Test::Deep qw(cmp_deeply shallow);
use Test::More 0.96;

sub tearDown {
	my ($self) = @_;
	$self->clearMocks();
	return EXIT_SUCCESS;
}

sub _tempFile {
	my ($self) = @_;
	my ($fh, $file) = tempfile();
	print {$fh} $self->uniqueStr();
	close($fh) or die("Cannot close '$file': $ERRNO");
	return $file;
}

sub _mockBackend {
	my ($self, $existing) = @_;
	my $backend = Daybo::Twitch::TagWrap::Backend::MP3->new();

	$self->mock('Daybo::Twitch::TagWrap', 'getBackendForExt', sub { return $backend });
	$self->mock('Daybo::Twitch::TagWrap::Backend::MP3', 'readTags', sub { return $existing });
	$self->mock('Daybo::Twitch::TagWrap::Backend::MP3', 'deleteTags', sub { return });
	$self->mock('Daybo::Twitch::TagWrap::Backend::MP3', 'writeTags', sub { return });
	$self->mock('Daybo::Twitch::Retag', '__log', sub { return });
	$self->mock('Daybo::Twitch::Retag', '__marker', sub { return '' });
	$self->mock('Daybo::Twitch::Retag', '__logTagChanges', sub { return 3 });

	return $backend;
}

sub testNoop {
	my ($self) = @_;
	plan tests => 3;

	my $file = $self->_tempFile();
	my $sut = Daybo::Twitch::Retag->new(noop => 1);
	$sut->__originalProgramName($PROGRAM_NAME);
	$self->_mockBackend({ artist => 'Old' });

	my @result = $sut->__tagPerProcess($file, 'mp3', 25, 'Artist', 'Album', 'Track', '2024');

	cmp_deeply(\@result, [0, 3], 'returns unmodified result and change count in noop mode');
	cmp_deeply($self->mockCallsWithObject('Daybo::Twitch::TagWrap::Backend::MP3', 'deleteTags'), [], 'does not delete tags in noop mode');
	cmp_deeply($self->mockCallsWithObject('Daybo::Twitch::TagWrap::Backend::MP3', 'writeTags'), [], 'does not write tags in noop mode');

	unlink($file);
	return EXIT_SUCCESS;
}

sub testSkipTimestamp {
	my ($self) = @_;
	plan tests => 2;

	my $file = $self->_tempFile();
	my $sut = Daybo::Twitch::Retag->new(mtime => 60);
	$sut->__originalProgramName($PROGRAM_NAME);
	$self->_mockBackend({ artist => 'Old' });

	my @result = $sut->__tagPerProcess($file, 'mp3', 25, 'Artist', 'Album', 'Track', '2024');

	cmp_deeply(\@result, [0, 0], 'skips file newer than mtime threshold');
	cmp_deeply($self->mockCallsWithObject('Daybo::Twitch::TagWrap', 'getBackendForExt'), [], 'does not read tags after timestamp skip');

	unlink($file);
	return EXIT_SUCCESS;
}

sub testSkipUnchanged {
	my ($self) = @_;
	plan tests => 2;

	my $file = $self->_tempFile();
	my $artist = 'Artist';
	my $album = 'Album';
	my $track = 'Track';
	my $year = '2024';
	my $comment = "Generated by $Daybo::Twitch::Retag::URL";
	my $sut = Daybo::Twitch::Retag->new();
	$sut->__originalProgramName($PROGRAM_NAME);
	$self->_mockBackend({
		artist => $artist,
		album => $album,
		track => $track,
		year => $year,
		comment => $comment,
	});

	my @result = $sut->__tagPerProcess($file, 'mp3', 25, $artist, $album, $track, $year);

	cmp_deeply(\@result, [0, 0], 'skips when existing tags already match');
	cmp_deeply($self->mockCallsWithObject('Daybo::Twitch::Retag', '__logTagChanges'), [], 'does not log changes for unchanged tags');

	unlink($file);
	return EXIT_SUCCESS;
}

sub testSuccess {
	my ($self) = @_;
	plan tests => 3;

	my $file = $self->_tempFile();
	my $sut = Daybo::Twitch::Retag->new();
	$sut->__originalProgramName($PROGRAM_NAME);
	my $backend = $self->_mockBackend({ artist => 'Old' });

	my @result = $sut->__tagPerProcess($file, 'mp3', 25, 'Artist', 'Album', 'Track', '2024');

	cmp_deeply(\@result, [1, 3], 'returns modified result and change count');
	cmp_deeply($self->mockCallsWithObject('Daybo::Twitch::TagWrap::Backend::MP3', 'deleteTags'), [[
		shallow($backend),
		$file,
	]], 'deletes existing tags');
	cmp_deeply($self->mockCallsWithObject('Daybo::Twitch::TagWrap::Backend::MP3', 'writeTags'), [[
		shallow($backend),
		$file,
		'Artist',
		'Album',
		'Track',
		'2024',
		"Generated by $Daybo::Twitch::Retag::URL",
	]], 'writes replacement tags') or diag(explain($self->mockCallsWithObject('Daybo::Twitch::TagWrap::Backend::MP3', 'writeTags')));

	unlink($file);
	return EXIT_SUCCESS;
}

package main; ## no critic (Modules::ProhibitMultiplePackages)
use strict;
use warnings;
exit(Retag_tagPerProcess_Tests->new->run);
